import streamlit as st
import pandas as pd
import plotly.express as px

from utils.api import (
    get_history,
    get_paper_analysis
)


# =========================================================
# PAGE CONFIG
# =========================================================

st.set_page_config(

    page_title="Analysis Report",

    page_icon="📄",

    layout="wide"

)


# =========================================================
# TITLE
# =========================================================

st.title(
    "📄 Detailed Research Paper Analysis"
)


st.write(
    "Complete analysis report generated by "
    "ResponsibleMetrics AI."
)


st.divider()


# =========================================================
# LOAD HISTORY
# =========================================================

history_result = get_history()


if "error" in history_result:

    st.error(
        f"Unable to load analysis history: "
        f"{history_result['error']}"
    )

    st.stop()


papers = history_result.get(
    "papers",
    []
)


if not papers:

    st.warning(
        "No paper analyses available. "
        "Please analyze a research paper first."
    )

    st.stop()


# =========================================================
# PAPER SELECTOR
# =========================================================

paper_options = {
    f"ID {paper['id']} - {paper.get('title') or paper.get('filename')}": paper["id"]
    for paper in papers
}

# Match selected_paper_id from session_state (e.g. when clicked "View Analysis" on a row)
default_index = 0
selected_id_from_state = st.session_state.get("selected_paper_id")
if selected_id_from_state is not None:
    for idx, pid in enumerate(paper_options.values()):
        if pid == selected_id_from_state:
            default_index = idx
            break

selected_label = st.selectbox(
    "Select Paper Analysis",
    list(paper_options.keys()),
    index=default_index
)

selected_paper_id = paper_options[selected_label]
st.session_state["selected_paper_id"] = selected_paper_id


# =========================================================
# LOAD FULL PAPER ANALYSIS
# =========================================================

analysis_result = get_paper_analysis(selected_paper_id)

if "error" in analysis_result:
    st.error(f"Unable to load paper analysis: {analysis_result['error']}")
    st.stop()


# =========================================================
# SAFE VALUES & JSON CONVERSION
# =========================================================

import json

def to_dict(val):
    if isinstance(val, dict):
        return val
    if isinstance(val, str):
        try:
            parsed = json.loads(val)
            if isinstance(parsed, dict):
                return parsed
            if isinstance(parsed, list):
                return {"items": parsed}
        except Exception:
            return {}
    return {}

paper_info = to_dict(analysis_result.get("paper_information"))
responsible_metrics = to_dict(analysis_result.get("responsible_metrics"))
principle_summary = to_dict(analysis_result.get("principle_summary"))
research_gap_summary = to_dict(analysis_result.get("research_gap_summary"))
nlp_analysis = to_dict(analysis_result.get("nlp_analysis"))
bibliometric_analysis = to_dict(analysis_result.get("bibliometric_analysis"))
responsible_metrics_analysis = to_dict(analysis_result.get("responsible_metrics_analysis"))
principle_analysis = to_dict(analysis_result.get("principle_analysis"))
research_gap_analysis = to_dict(analysis_result.get("research_gap_analysis"))
multi_level_analysis = to_dict(analysis_result.get("multi_level_analysis"))


# =========================================================
# PAPER INFORMATION
# =========================================================

st.header(
    "📄 Paper Information"
)


col1, col2, col3, col4 = st.columns(4)


with col1:

    st.metric(

        "Paper ID",

        analysis_result.get(
            "id",
            "N/A"
        )

    )


with col2:

    st.metric(

        "Pages",

        paper_info.get(
            "page_count",
            0
        )

    )


with col3:

    st.metric(

        "Words",

        paper_info.get(
            "word_count",
            0
        )

    )


with col4:

    st.metric(

        "Characters",

        paper_info.get(
            "character_count",
            0
        )

    )


st.subheader(

    analysis_result.get(
        "title"
    )
    or
    "Untitled Research Paper"

)


st.write(

    f"**Filename:** "
    f"{analysis_result.get('filename', 'N/A')}"

)


st.divider()


# =========================================================
# EVALUATION OVERVIEW
# =========================================================

st.header(
    "📊 Evaluation Overview"
)


responsible_score = responsible_metrics.get(
    "score",
    0
)


compliance_score = principle_summary.get(
    "compliance_score",
    0
)


novelty_level = research_gap_summary.get(
    "novelty_level",
    "Unknown"
)


average_similarity = research_gap_summary.get(
    "average_similarity",
    0
)


try:

    responsible_score = float(
        responsible_score or 0
    )

except:

    responsible_score = 0


try:

    compliance_score = float(
        compliance_score or 0
    )

except:

    compliance_score = 0


try:

    average_similarity = float(
        average_similarity or 0
    )

except:

    average_similarity = 0


col1, col2, col3, col4 = st.columns(4)


with col1:

    st.metric(

        "Responsible Score",

        f"{responsible_score:.2f}%"

    )


with col2:

    st.metric(

        "Principle Compliance",

        f"{compliance_score:.2f}%"

    )


with col3:

    st.metric(

        "Novelty Level",

        novelty_level

    )


with col4:

    st.metric(

        "Literature Similarity",

        f"{average_similarity:.4f}"

    )


st.divider()

# =========================================================
# AUDIT REPORT DOWNLOAD
# =========================================================
def build_markdown_audit_report():
    import json

    def to_dict(val):
        if isinstance(val, dict):
            return val
        if isinstance(val, str):
            try:
                return json.loads(val)
            except Exception:
                return {}
        return {}

    nlp_d = to_dict(nlp_analysis)
    bib_d = to_dict(bibliometric_analysis)
    principle_d = to_dict(principle_analysis)
    gap_d = to_dict(research_gap_analysis)

    title_str = analysis_result.get("title") or analysis_result.get("filename") or "Research Paper"
    report_lines = [
        f"# ResponsibleMetrics AI: Evaluation Audit Report",
        f"**Paper Title:** {title_str}",
        f"**Analysis ID:** {analysis_result.get('id')} | **Filename:** {analysis_result.get('filename')}",
        f"**Generated On:** {analysis_result.get('created_at', 'N/A')}",
        "",
        "## Executive Summary Scores",
        f"- **Responsible Metrics Score:** {responsible_score:.2f}%",
        f"- **Principle Compliance Score:** {compliance_score:.2f}%",
        f"- **Research Novelty Level:** {novelty_level}",
        f"- **Average Literature Similarity:** {average_similarity:.4f}",
        "",
        "## 1. Natural Language Processing (NLP) Findings",
        f"- **Extracted Keywords:** {', '.join([k if isinstance(k, str) else k.get('keyword', '') for k in nlp_d.get('keywords', [])[:8]])}",
        f"- **Research Problems Identified:**",
    ]
    for p in (nlp_d.get("research_problems") or ["None identified"]):
        report_lines.append(f"  - {p}")
    report_lines.append("- **Contributions:**")
    for c in (nlp_d.get("research_contributions") or ["None identified"]):
        report_lines.append(f"  - {c}")
    report_lines.append("- **Key Findings:**")
    for f in (nlp_d.get("key_findings") or ["None identified"]):
        report_lines.append(f"  - {f}")

    oa_val = bib_d.get("open_access")
    oa_str = oa_val.get("is_oa", "Unknown") if isinstance(oa_val, dict) else "Unknown"

    report_lines.extend([
        "",
        "## 2. Bibliometric Profile (OpenAlex Integration)",
        f"- **Citations (Cited by Count):** {bib_d.get('citation_count', 'N/A')}",
        f"- **Publication Year:** {bib_d.get('publication_year', 'N/A')}",
        f"- **Source / Journal:** {bib_d.get('journal', 'N/A')}",
        f"- **Open Access:** {oa_str}",
        "",
        "## 3. Responsible Research Assessment (Leiden & DORA Principles)",
    ])

    practices = principle_d.get("responsible_practices", [])
    if practices:
        report_lines.append("### Adherent Responsible Practices:")
        for pr in practices:
            report_lines.append(f"- [x] **{pr.get('category', 'Practice')}**: {pr.get('principle', '')}")
    else:
        report_lines.append("- No explicit adherence statements detected.")

    misuses = principle_d.get("potential_misuse", [])
    if misuses:
        report_lines.append("\n### Detected Indicator Misuse / Red Flags:")
        for m in misuses:
            report_lines.append(f"- [!] **[{m.get('severity', 'WARNING').upper()}] {m.get('message', '')}**")
            if m.get("explanation"):
                report_lines.append(f"  - *Explanation:* {m.get('explanation')}")
            if m.get("remediation"):
                report_lines.append(f"  - *Remediation:* {m.get('remediation')}")

    recs = principle_d.get("recommendations", [])
    if recs:
        report_lines.append("\n### Actionable Recommendations:")
        for r in recs:
            report_lines.append(f"1. {r}")

    report_lines.extend([
        "",
        "## 4. Research Gap & Novelty Analysis",
        f"- **Novelty Rating:** {novelty_level}",
        f"- **Gap Summary:** {gap_d.get('potential_gap', 'N/A')}",
        "",
        "---",
        "*Report certified by ResponsibleMetrics AI Framework for Responsible Bibliometrics.*"
    ])
    return "\n".join(report_lines)

audit_report_text = build_markdown_audit_report()
col_dl1, col_dl2 = st.columns([1, 3])
with col_dl1:
    st.download_button(
        label="📥 Download Audit Report (.md)",
        data=audit_report_text,
        file_name=f"ResponsibleMetrics_Audit_{analysis_result.get('id', 'paper')}.md",
        mime="text/markdown",
        use_container_width=True
    )
with col_dl2:
    st.caption("Download formal evaluation audit including Leiden/DORA compliance, misuse detection, and actionable remediation guidelines.")

st.divider()


# =========================================================
# TABS
# =========================================================

# =========================================================
# TABS
# =========================================================

tab1, tab2, tab3, tab4, tab5, tab6 = st.tabs([
    "🧠 NLP Analysis",
    "📊 Bibliometrics",
    "⚖️ Responsible Metrics",
    "🔍 Principles",
    "🧬 Research Gap",
    "🏗️ Multi-Level Framework"
])


# =========================================================
# TAB 1: NLP ANALYSIS
# =========================================================

with tab1:
    st.header("🧠 Natural Language Processing Findings")

    # 1. KEYWORDS
    st.subheader("🔑 Extracted Key Scientific Phrases (KeyBERT)")
    keywords = nlp_analysis.get("keywords", [])
    if keywords:
        cols = st.columns(3)
        for i, kw in enumerate(keywords):
            with cols[i % 3]:
                if isinstance(kw, dict):
                    kw_name = kw.get("keyword") or kw.get("text") or kw.get("name") or str(kw)
                    score = kw.get("score")
                    score_str = f" • Relevance: {float(score):.2f}" if score is not None else ""
                    st.info(f"**{kw_name}**{score_str}")
                else:
                    st.info(f"**{kw}**")
    else:
        st.info("No keyphrases detected in the uploaded text.")

    st.write("")

    # 2. RESEARCH PROBLEM
    st.subheader("🎯 Research Problem Statement")
    prob_list = nlp_analysis.get("research_problem", [])
    if isinstance(prob_list, str):
        prob_list = [prob_list] if prob_list.strip() else []

    if prob_list:
        with st.container(border=True):
            for item in prob_list:
                st.markdown(f"• {item}")
    else:
        st.info("No explicit research problem statement extracted.")

    # 3. METHODOLOGY
    st.subheader("⚙️ Academic Methodology & Approach")
    method_list = nlp_analysis.get("methodology", [])
    if isinstance(method_list, str):
        method_list = [method_list] if method_list.strip() else []

    if method_list:
        with st.container(border=True):
            for item in method_list:
                st.markdown(f"• {item}")
    else:
        st.info("No methodology section detected.")

    # 4. RESEARCH CONTRIBUTIONS
    st.subheader("💡 Key Research Contributions")
    contrib_list = nlp_analysis.get("contributions") or nlp_analysis.get("research_contributions") or []
    if isinstance(contrib_list, str):
        contrib_list = [contrib_list] if contrib_list.strip() else []

    if contrib_list:
        with st.container(border=True):
            for item in contrib_list:
                st.markdown(f"• {item}")
    else:
        st.info("No explicit contributions section detected.")

    # 5. KEY FINDINGS
    st.subheader("📊 Key Findings & Results")
    findings_list = nlp_analysis.get("key_findings", [])
    if isinstance(findings_list, str):
        findings_list = [findings_list] if findings_list.strip() else []

    if findings_list:
        with st.container(border=True):
            for item in findings_list:
                st.markdown(f"• {item}")
    else:
        st.info("No key findings detected.")


# =========================================================
# TAB 2: BIBLIOMETRICS
# =========================================================

with tab2:
    st.header("📊 Bibliometric Profile & Citation Records")

    has_live_bib = bool(bibliometric_analysis and any(bibliometric_analysis.values()))

    if has_live_bib and (bibliometric_analysis.get("citation_count") is not None or bibliometric_analysis.get("publication_year")):
        col_b1, col_b2, col_b3, col_b4 = st.columns(4)
        oa_val = bibliometric_analysis.get("open_access", {})
        oa_status = oa_val.get("is_oa", "Unknown") if isinstance(oa_val, dict) else "Unknown"

        with col_b1:
            st.metric("Total Citations", bibliometric_analysis.get("citation_count", 0))
        with col_b2:
            st.metric("Publication Year", bibliometric_analysis.get("publication_year", "N/A"))
        with col_b3:
            st.metric("Journal / Venue", str(bibliometric_analysis.get("journal", "N/A"))[:28])
        with col_b4:
            st.metric("Open Access", "✅ Open Access" if oa_status is True else "🔒 Closed / Unverified")

        with st.container(border=True):
            st.subheader("📄 Verified Publication Metadata (OpenAlex API)")
            if bibliometric_analysis.get("title"):
                st.write(f"**Indexed Title:** {bibliometric_analysis.get('title')}")
            if bibliometric_analysis.get("authors"):
                authors = bibliometric_analysis.get("authors")
                if isinstance(authors, list):
                    author_names = [a.get("name", str(a)) if isinstance(a, dict) else str(a) for a in authors]
                    st.write(f"**Authors:** {', '.join(author_names)}")
                else:
                    st.write(f"**Authors:** {authors}")
            if bibliometric_analysis.get("doi"):
                doi = bibliometric_analysis.get("doi")
                st.markdown(f"**DOI:** [{doi}](https://doi.org/{doi})")
            if bibliometric_analysis.get("concepts"):
                concepts = bibliometric_analysis.get("concepts", [])
                concept_names = [c.get("display_name", str(c)) if isinstance(c, dict) else str(c) for c in concepts[:6]]
                st.write(f"**Scientific Concepts:** {', '.join(concept_names)}")
    else:
        with st.container(border=True):
            st.subheader("📄 Local Bibliometric Manuscript Profile")
            st.info(
                "ℹ️ **Local NLP Extraction Active:** This manuscript was evaluated using local text parsing. "
                "Live OpenAlex citation counts and journal metrics are linked whenever an indexed DOI or exact title is matched in the global catalog."
            )
            col_l1, col_l2, col_l3 = st.columns(3)
            with col_l1:
                st.metric("Pages Extracted", paper_info.get("page_count", 0))
            with col_l2:
                st.metric("Word Count", paper_info.get("word_count", 0))
            with col_l3:
                st.metric("Character Count", paper_info.get("character_count", 0))


# =========================================================
# TAB 3: RESPONSIBLE METRICS
# =========================================================

with tab3:
    st.header("⚖️ Responsible Metrics Evaluation")

    overall_data = responsible_metrics_analysis.get("overall", {})
    rating_text = overall_data.get("rating") or responsible_metrics.get("rating", "Standard Evaluation")
    bonus_pts = overall_data.get("bibliometric_bonus", 0)

    col_r1, col_r2, col_r3 = st.columns(3)
    with col_r1:
        st.metric("Responsible Metrics Score", f"{responsible_score:.2f}%")
    with col_r2:
        st.metric("Evaluation Rating", rating_text)
    with col_r3:
        st.metric("Bibliometric Bonus", f"+{bonus_pts} pts")

    st.divider()

    # The 6 Assessment Dimensions
    st.subheader("📐 Multi-Dimensional Framework Assessment (6 Dimensions)")
    dimensions = responsible_metrics_analysis.get("dimensions", {})

    dim_labels = {
        "contextual_evaluation": ("Contextual Evaluation", "Considers evaluation context, tailored goals, and appropriate indicator scope."),
        "transparency": ("Transparency & Reproducibility", "Uses open, auditable methods and verifiable public citations."),
        "metric_diversity": ("Metric Diversity", "Avoids relying on a single indicator (e.g. JIF or citation count alone)."),
        "qualitative_evidence": ("Qualitative & Peer Evidence", "Integrates narrative statements, qualitative portfolio, and peer review."),
        "discipline_awareness": ("Discipline Awareness", "Accounts for field-specific differences in publication and citation speed."),
        "limitations_awareness": ("Limitations Awareness", "Explicitly warns against indicator bias, gaming, and misinterpretation.")
    }

    if dimensions:
        dim_keys = list(dimensions.keys())
        for i in range(0, len(dim_keys), 2):
            col_d1, col_d2 = st.columns(2)
            with col_d1:
                k1 = dim_keys[i]
                d1 = dimensions[k1]
                title1, desc1 = dim_labels.get(k1, (k1.replace("_", " ").title(), ""))
                score1 = float(d1.get("score", 0))
                with st.container(border=True):
                    st.markdown(f"**{title1}**")
                    st.caption(desc1)
                    st.progress(min(1.0, max(0.0, score1 / 100.0)))
                    st.write(f"**Score:** {score1:.1f}% | **Weight:** {d1.get('weight', 0)}% | **Contribution:** {d1.get('weighted_contribution', 0):.1f} pts")
                    kws = d1.get("matched_keywords", [])
                    if kws:
                        st.write(f"*Matched concepts:* {', '.join(kws[:6])}")

            if i + 1 < len(dim_keys):
                with col_d2:
                    k2 = dim_keys[i + 1]
                    d2 = dimensions[k2]
                    title2, desc2 = dim_labels.get(k2, (k2.replace("_", " ").title(), ""))
                    score2 = float(d2.get("score", 0))
                    with st.container(border=True):
                        st.markdown(f"**{title2}**")
                        st.caption(desc2)
                        st.progress(min(1.0, max(0.0, score2 / 100.0)))
                        st.write(f"**Score:** {score2:.1f}% | **Weight:** {d2.get('weight', 0)}% | **Contribution:** {d2.get('weighted_contribution', 0):.1f} pts")
                        kws2 = d2.get("matched_keywords", [])
                        if kws2:
                            st.write(f"*Matched concepts:* {', '.join(kws2[:6])}")
    else:
        st.info("Detailed dimensional breakdown not available.")


# =========================================================
# TAB 4: PRINCIPLES (LEIDEN & DORA)
# =========================================================

with tab4:
    st.header("🔍 Leiden Manifesto & DORA Principles Compliance")

    st.metric("Principle Compliance Score", f"{compliance_score:.2f}%")

    misuses = principle_analysis.get("potential_misuse", [])
    practices = principle_analysis.get("responsible_practices", [])
    recs = principle_analysis.get("recommendations", [])

    st.subheader("⚠️ Detected Indicator Misuses & Red Flags")
    if misuses:
        for m in misuses:
            severity = m.get("severity", "medium").upper()
            msg = m.get("message") or m.get("category")
            with st.container(border=True):
                st.error(f"🚨 **[{severity}] {msg}**")
                if m.get("explanation"):
                    st.markdown(f"**Why this is a violation:** {m['explanation']}")
                if m.get("remediation"):
                    st.info(f"💡 **Actionable Remediation:** {m['remediation']}")
                if m.get("evidence"):
                    with st.expander("🔎 View Text Evidence from Paper"):
                        for ev in m["evidence"]:
                            st.markdown(f"> *\"{ev.strip()}\"*")
    else:
        st.success("✅ **Zero Misuses Detected:** This paper does not violate DORA or Leiden Manifesto guidelines (no unadjusted cross-field comparisons or rigid journal impact factor filtering).")

    st.subheader("✅ Adherent Responsible Practices")
    if practices:
        for pr in practices:
            category_title = pr.get("category", "Responsible Assessment").replace("_", " ").title()
            with st.container(border=True):
                st.markdown(f"**✅ {category_title}:** {pr.get('principle', '')}")
                if pr.get("evidence"):
                    with st.expander("🔎 View Text Evidence from Paper"):
                        for ev in pr["evidence"]:
                            st.markdown(f"> *\"{ev.strip()}\"*")
    else:
        st.info("No explicit responsible practice statements detected.")

    st.subheader("💡 Actionable Recommendations")
    if recs:
        for i, r in enumerate(recs, 1):
            st.markdown(f"**{i}.** {r}")
    else:
        st.write("• Continue maintaining qualitative peer-review context alongside metric assessments.")


# =========================================================
# TAB 5: RESEARCH GAP & NOVELTY
# =========================================================

with tab5:
    st.header("🧬 Research Gap Detection & Literature Landscape")

    col_g1, col_g2, col_g3 = st.columns(3)
    with col_g1:
        st.metric("Novelty Level", novelty_level)
    with col_g2:
        st.metric("Average Literature Similarity", f"{average_similarity:.4f}")
    with col_g3:
        st.metric("Benchmark Papers Compared", research_gap_analysis.get("literature_count", 35))

    gap_stmt = research_gap_analysis.get("potential_gap")
    if gap_stmt:
        with st.container(border=True):
            st.subheader("🎯 Identified Research Gap Statement")
            st.info(f"**Novel Opportunity:** {gap_stmt}")

    # Interactive 2D Scatter Plot
    clustering_info = research_gap_analysis.get("clustering", {})
    scatter_points = clustering_info.get("scatter_points", [])
    if scatter_points:
        st.subheader("🗺️ Thematic Literature Map (2D PCA Semantic Projection)")
        df_points = pd.DataFrame(scatter_points)
        fig = px.scatter(
            df_points,
            x="x",
            y="y",
            color="type",
            hover_name="title",
            symbol="type",
            title="Semantic Projection of Literature Clusters vs Uploaded Paper",
            labels={"x": "Semantic Dimension 1 (PCA)", "y": "Semantic Dimension 2 (PCA)"}
        )
        fig.update_traces(marker=dict(size=13, line=dict(width=1.5, color='DarkSlateGrey')))
        st.plotly_chart(fig, use_container_width=True)

    similar_papers = research_gap_analysis.get("similar_papers", [])

    # Benchmark Similarity Distribution Chart
    if isinstance(similar_papers, list) and similar_papers:
        chart_rows = []
        for p in similar_papers:
            p_dict = to_dict(p) if isinstance(p, (dict, str)) else {}
            t = str(p_dict.get("title", "Benchmark Paper"))[:45]
            try:
                sim_pct = round(float(p_dict.get("similarity", 0) or 0) * 100, 2)
            except Exception:
                sim_pct = 0.0
            chart_rows.append({"Paper": t, "Similarity (%)": sim_pct})

        if chart_rows:
            df_chart = pd.DataFrame(chart_rows).sort_values(by="Similarity (%)", ascending=True)
            fig_sim = px.bar(
                df_chart,
                x="Similarity (%)",
                y="Paper",
                orientation="h",
                title="Benchmark Literature Similarity Match (%)",
                text="Similarity (%)",
                range_x=[0, max(30, float(df_chart["Similarity (%)"].max() * 1.25))]
            )
            fig_sim.update_layout(yaxis_title="", xaxis_title="Similarity Score (%)")
            st.plotly_chart(fig_sim, use_container_width=True)

    # Similar Papers Cards
    st.subheader("📚 Top Similar Benchmark Papers")
    if isinstance(similar_papers, list) and similar_papers:
        for idx, paper_item in enumerate(similar_papers, 1):
            p = to_dict(paper_item) if isinstance(paper_item, (dict, str)) else {}
            p_title = p.get("title", f"Benchmark Paper {idx}")
            p_year = p.get("year", "N/A")
            p_id = p.get("id", "N/A")
            p_venue = p.get("venue", "")
            try:
                sim_val_num = float(p.get("similarity", 0) or 0)
                sim_pct = sim_val_num * 100
            except Exception:
                sim_val_num = 0.0
                sim_pct = 0.0

            with st.container(border=True):
                col_p1, col_p2 = st.columns([3, 1])
                with col_p1:
                    st.markdown(f"**{idx}. {p_title}**")
                    meta_bits = []
                    if p_year and p_year != "N/A":
                        meta_bits.append(f"📅 Year: {p_year}")
                    if p_id and p_id != "N/A":
                        meta_bits.append(f"🆔 OpenAlex ID: {p_id}")
                    if p_venue:
                        meta_bits.append(f"🏛️ Venue: {p_venue}")
                    if meta_bits:
                        st.caption(" • ".join(meta_bits))
                with col_p2:
                    st.metric("Similarity Match", f"{sim_pct:.2f}%")
                st.progress(min(1.0, max(0.0, sim_val_num)))
    else:
        st.info("No benchmark literature papers matched.")

    # Underexplored Keywords Cards
    st.subheader("🌱 Underexplored Scientific Themes")
    underexplored = research_gap_analysis.get("underexplored_keywords", [])
    if isinstance(underexplored, list) and underexplored:
        col_u1, col_u2 = st.columns(2)
        for idx, item in enumerate(underexplored):
            target_col = col_u1 if idx % 2 == 0 else col_u2
            with target_col:
                with st.container(border=True):
                    if isinstance(item, dict):
                        kw = item.get("keyword", "Theme")
                        freq = item.get("frequency", 0)
                        st.markdown(f"🔬 **{kw}**")
                        st.caption(f"Literature Frequency: **{freq} occurrences** (High Novelty Potential)")
                    else:
                        st.markdown(f"🔬 **{item}**")
                        st.caption("High Novelty Potential")
    else:
        st.info("No underexplored themes identified.")


# =========================================================
# TAB 6: MULTI-LEVEL FRAMEWORK
# =========================================================

with tab6:
    st.header("🏗️ Four-Level Responsible Evaluation Framework")

    ml_score = multi_level_analysis.get("overall_score", 0.0)
    ml_rating = multi_level_analysis.get("overall_rating", "Evaluated")

    col_m1, col_m2 = st.columns(2)
    with col_m1:
        st.metric("Multi-Level Overall Score", f"{float(ml_score):.2f}%")
    with col_m2:
        st.metric("Framework Maturity Rating", ml_rating)

    levels_data = multi_level_analysis.get("levels") or multi_level_analysis

    level_specs = [
        ("indicator_level", "Level 1: Indicator Level (Metric Diversity & Limits)", "Checks indicator variety, fitness for purpose, and explicit warning of metric limitations."),
        ("researcher_level", "Level 2: Researcher Level (Fairness & DORA)", "Protects individual scientists against journal-level shortcuts; emphasizes peer review and junior researchers."),
        ("institutional_level", "Level 3: Institutional Level (Field Normalization)", "Ensures comparisons across university departments normalize citation differences across fields."),
        ("system_policy_level", "Level 4: System & Policy Level (Open Data & Integrity)", "Enforces open data transparency (OpenAlex), verifiable records, and checks against citation cartels.")
    ]

    col_lvl1, col_lvl2 = st.columns(2)
    for idx, (l_key, l_title, l_desc) in enumerate(level_specs):
        l_info = to_dict(levels_data.get(l_key))
        target_col = col_lvl1 if idx % 2 == 0 else col_lvl2
        with target_col:
            with st.container(border=True):
                st.subheader(l_title)
                st.caption(l_desc)
                try:
                    l_score = float(l_info.get("score", 0) or 0)
                except Exception:
                    l_score = 0.0
                st.progress(min(1.0, max(0.0, l_score / 100.0)))
                st.write(f"**Score:** {l_score:.1f}% | **Rating:** {l_info.get('rating', 'Evaluated')} | **Coverage:** {l_info.get('coverage', 'N/A')}")
                matched_kw = l_info.get("matched_keywords", [])
                if isinstance(matched_kw, list) and matched_kw:
                    st.write(f"*Concept indicators:* {', '.join([str(x) for x in matched_kw[:6]])}")